import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import SignOutButton from "@/components/sign-out";
import Providers from "./providers";
import Profile from "@/components/profile";
import Menu from "@/components/menu";


export const metadata: Metadata = {
  title: "Owp lists",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Menu />
              <Profile />
              <SignOutButton />
          {children}
        </body>
      </Providers>
    </html>
  );
}
