import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Menu from "@/components/menu";
// import { GoogleTagManager } from '@next/third-parties/google'
import GoogleAalytics from "@/components/google_analytics";

export const metadata: Metadata = {
  title: "Owp lists",
  description: "Generated by create next app",
};

// const GA_ID = process.env.GOOGLE_ANALYTICS_ID || ""

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Menu />
          {children}
        </body>
      </Providers>
      {/* <GoogleTagManager gtmId={GA_ID} />  */}
      <GoogleAalytics />
    </html>
  );
}
