import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Menu from "@/components/menu";


export const metadata: Metadata = {
  title: "Owp lists",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Menu />
          {children}
        </body>
      </Providers>
    </html>
  );
}
